version: '3'

services:
  element:
    image: vectorim/element-web:latest
    container_name: element
    restart: unless-stopped
    volumes:
      - /nfs/cistern/docker/apps/sczi/element/element-config.json:/app/config.json

networks:
  default:
    external:
      name: vtluug-network
