version: '3'

services:
  pyqdb:
    restart: unless-stopped
    env_file: pyqdb.env
    image: vtluug/pyqdb
    container_name: pyqdb
    volumes:
      - /nfs/cistern/docker/data/pyqdb/quotes.db:/app/quotes.db

networks:
  default:
    external:
      name: vtluug-network
