services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    volumes:
      - /nfs/cistern/docker/data/ipex/openwebui/:/app/backend/data
    environment:
      - PORT=8081
    privileged: true
    restart: unless-stopped

networks:
  default:
    external:
      name: vtluug-network