version: '3'

services:
  mediawiki:
    restart: unless-stopped
    depends_on:
      - database
    image: mediawiki:lts
    networks:
      - vtluug-network
    volumes:
      - /nfs/cistern/docker/data/wiki/images:/var/www/html/images
      - ./config/LocalSettings.php:/var/www/LocalSettings.php:ro
      - ./config/LocalSettings_vtluug.php:/var/www/LocalSettings_vtluug.php:ro
      - ./config/LocalSettings_gobblerpedia.php:/var/www/LocalSettings_gobblerpedia.php:ro
      - ./config/secrets.php:/var/www/secrets.php:ro
  database:
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: mw
      MYSQL_USER: mw_user
    image: mariadb
    volumes:
      - /nfs/cistern/docker/data/wiki/mysql:/var/lib/mysql
