version: '3'

services:
  mediawiki:
    restart: unless-stopped
    image: mediawiki
    volumes:
      - /nfs/cistern/docker/data/wiki/images:/var/www/html/images
      - ./config/LocalSettings.php:/var/www/LocalSettings.php
      - ./config/LocalSettings_vtluug.php:/var/www/LocalSettings_vtluug.php
      - ./config/LocalSettings_gobblerpedia.php:/var/www/LocalSettings_gobblerpedia.php
    ports:
      - 127.0.0.1:7001:80
  database:
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: mediawiki
      MYSQL_USER: mediawikiuser
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    image: mariadb
