version: '3'

services:
  letsencrypt:
    restart: unless-stopped
    image: linuxserver/swag
    cap_add:
      - NET_ADMIN
    environment:
      PGID: 1000
      PUID: 1000
      EMAIL: sysadmin@vtluug.org
      # URL field must be working since nginx only starts if letsencrypt works
      URL: vtluug.org
      SUBDOMAINS: awm
      #EXTRA_DOMAINS: gobblerpedia.org,www.gobblerpedia.org,hokieprivacy.org,www.hokieprivacy.org,distributions.pconte.me
      VALIDATION: html # TODO Switch to dns + gandi api once pr is merged
      TZ: America/New_York
    volumes:
      # nginx config
      - /nfs/cistern/docker/data/nginx/config:/config
      - ./nginx.conf:/config/nginx/nginx.conf:ro
      - ./ssl.conf:/config/nginx/ssl.conf:ro
      - ./site-confs:/config/nginx/site-confs:ro
      - ./jail.local:/config/jail2ban/jail.local:ro
    ports:
      - 2607:b400:0006:cc80:0000:0aff:fe62:0004:8781:8781

networks:
  default:
    external:
      name: vtluug-network
