version: '3'

services:
  linx:
    restart: unless-stopped
    image: andreimarcu/linx-server
    command: ['-sitename=linx', '-allowhotlink', '-fastcgi', '-remoteuploads', '-selifpath', 's', '-custompagespath', '/data/custom_pages']
    volumes:
      - /nfs/cistern/docker/data/linx/files:/data/files
      - /nfs/cistern/docker/data/linx/meta:/data/meta
      - /nfs/cistern/docker/data/linx/custom_pages:/data/custom_pages:ro

networks:
  default:
    external:
      name: vtluug-network
