services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      DIFFICULTY: "normal"
      ENABLE_WHITELIST: "TRUE"
      WHITELIST: "heavy_weather142,browzerhistory" #send an email to localhunter@vtluug.org to get on the whitelist
      ICON: "https://vtluug.org/w/images/thumb/a/a5/Hokie_tux.png/711px-Hokie_tux.png"
      RCON_CMDS_STARTUP: "kill @e[type=wither]" 
      # TYPE: "MODRINTH"
      # MODRINTH_MODPACK: /modpacks/huntersmodpack1.0.0.mrpack
    volumes:
      # attach the relative directory 'data' to the container' /data path
      - /nfs/cistern/docker/data/minecraft/data:/data
      - /nfs/cistern/docker/data/minecraft/modpacks:/modpacks:ro
