services:
  mc:
    image: itzg/minecraft-server
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      DIFFICULTY: "normal"
      VERSION: "1.20.1"
      TYPE: "FABRIC"
      OPS: |
        rock_lahbstah
      
      volumes:
      # attach the relative directory 'data' to the container' /data path
      - /nfs/cistern/docker/data/minecraft/data:/data
      - /nfs/cistern/docker/data/minecraft/modpacks:/modpacks:ro
