version: '3'

services:
  web:
    restart: unless-stopped
    image: philipconte/class_util
    volumes:
      - ./data:/data
    env_file: .env
    environment:
      - DATABASE_URL=postgres://postgres@db/class_util_db
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=class_util_db
