version: '3'

services:
  web:
    restart: unless-stopped
    image: philipconte/class_util
    container_name: classutil
    volumes:
      - /nfs/cistern/docker/data/class_util:/data
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres
    env_file: .env
    environment:
      - POSTGRES_DB=class_util_db

networks:
  default:
    external:
      name: vtluug-network

