version: '3'

services:
  postgres:
    restart: unless-stopped
    env_file: .env
    image: postgres:9.4
    volumes:
      - /nfs/cistern/docker/data/funkwhale/postgres:/var/lib/postgresql/data

  redis:
    restart: unless-stopped
    env_file: .env
    image: redis:3
    volumes:
      - /nfs/cistern/docker/data/funkwhale/redis:/data

  celeryworker:
    restart: unless-stopped
    env_file: .env
    image: funkwhale/funkwhale:${FUNKWHALE_VERSION}
    command: celery -A funkwhale_api.taskapp worker -l INFO
    environment:
      - C_FORCE_ROOT=true
    volumes:
      - "${MUSIC_DIRECTORY_SERVE_PATH}:${MUSIC_DIRECTORY_PATH}:ro"
      - "${MEDIA_ROOT}:${MEDIA_ROOT}"

  celerybeat:
    restart: unless-stopped
    env_file: .env
    image: funkwhale/funkwhale:${FUNKWHALE_VERSION}
    command: celery -A funkwhale_api.taskapp beat -l INFO

  api:
    restart: unless-stopped
    env_file: .env
    image: funkwhale/funkwhale:${FUNKWHALE_VERSION}
    networks:
      - default
      - vtluug-network
    volumes:
      - "${MUSIC_DIRECTORY_SERVE_PATH}:${MUSIC_DIRECTORY_SERVE_PATH}:ro"
      - "${MEDIA_ROOT}:${MEDIA_ROOT}"
      - "${STATIC_ROOT}:${STATIC_ROOT}"
      - "${FUNKWHALE_FRONTEND_PATH}:/frontend"

networks:
  vtluug-network:
    external:
      name: vtluug-network
