version: '3'

services:
  hokieprivacy:
    restart: unless-stopped
    image: monachus/hugo
    command: ['hugo', 'server', '-d', '/usr/share/nginx/html']
    volumes:
      - ./site:/usr/share/blog:ro
      - /nfs/cistern/docker/data/hokieprivacy:/usr/share/nginx/html
