version: '3'

services:
  dex:
    restart: unless-stopped
    image: quay.io/dexidp/dex:latest
    # 'dex' cmd is already given as entrypoint
    env_file: dex.env
    command: ['serve', '/etc/dex/cfg/config.yml']
    volumes:
        - /nfs/cistern/docker/data/dex:/var/dex:rw
        - ./config.yml:/etc/dex/cfg/config.yml:ro
        # Requires host to be an IPA client
        - /etc/ipa/ca.crt:/etc/dex/cfg/ldap_ca.crt:ro

networks:
  default:
    external:
      name: vtluug-network
