version: '3'

services:
  dex:
    restart: unless-stopped
    image: quay.io/dexidp/dex:latest
    volumes:
        - /nfs/cistern/docker/data/dex/dex.db:/var/dex/dex.db
        - ./config.yml:/etc/dex/cfg/config.yml:ro
        # Requires host to be an IPA client
        - /etc/ipa/ca.crt:/etc/dex/cfg/ldap_ca.crt:ro

networks:
  default:
    external:
      name: vtluug-network
